trigger:
  - main # Adjust the branch name if needed

pool:
  name: "Default" # Name of your self-hosted agent pool

variables:
  # Define Azure Web App details
  azureWebAppName: "abbas-sleiman-webapp" # Replace with your Azure Web App name
  nodeVersion: "20.x"

steps:
  - task: UseNode@1
    inputs:
      version: $(nodeVersion)
    displayName: "Install Node.js"

  - script: |
      npm install
    displayName: "Install Dependencies"

  - task: AzureWebApp@1
    inputs:
      azureSubscription: "azureConnectionString"  # Replace with your Azure connection string
      appName: $(azureWebAppName)
      package: "$(System.DefaultWorkingDirectory)"  # Directly deploy from the repository
    displayName: "Deploy to Azure Web App"